/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{database}/-/sheets/api/workbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Name
                         * @default null
                         */
                        name?: string | null;
                        /**
                         * Sort Order
                         * @default null
                         */
                        sort_order?: number | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            workbook: components["schemas"]["WorkbookRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Sheets */
                            sheets: components["schemas"]["SheetRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Name
                         * @default Sheet 1
                         */
                        name?: string;
                        /**
                         * Color
                         * @default #8b774f
                         */
                        color?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sheet: components["schemas"]["SheetRecord"];
                            /** Columns */
                            columns: components["schemas"]["ColumnRecord"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Sheet Ids */
                        sheet_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Sheets */
                            sheets: components["schemas"]["SheetRecord"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sheet: components["schemas"]["SheetRecord"];
                            /** Columns */
                            columns: components["schemas"]["ColumnRecord"][];
                            /** Cells */
                            cells: components["schemas"]["CellRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Name
                         * @default null
                         */
                        name?: string | null;
                        /**
                         * Color
                         * @default null
                         */
                        color?: string | null;
                        /**
                         * Sort Order
                         * @default null
                         */
                        sort_order?: number | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sheet: components["schemas"]["SheetRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Ok
                             * @default true
                             */
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Changes */
                        changes?: components["schemas"]["CellChangeBody"][];
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Cells */
                            cells: components["schemas"]["CellRecord"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Columns */
                        columns?: components["schemas"]["ColumnChangeBody"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Columns */
                            columns: components["schemas"]["ColumnRecord"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/rows/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Row Indices */
                        row_indices?: number[];
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Deleted */
                            deleted: number[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/columns/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Col Indices */
                        col_indices?: number[];
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Deleted */
                            deleted: number[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/columns/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** At */
                        at: number;
                        /**
                         * Count
                         * @default 1
                         */
                        count?: number;
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Inserted */
                            inserted: number[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/columns/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Src Start */
                        src_start: number;
                        /** Src End */
                        src_end: number;
                        /** Dest Gap */
                        dest_gap: number;
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default null */
                            moved: components["schemas"]["MoveColumnsResult"] | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/rows/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Src Start */
                        src_start: number;
                        /** Src End */
                        src_end: number;
                        /** Dest Gap */
                        dest_gap: number;
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default null */
                            moved: components["schemas"]["MoveRowsResult"] | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @default null */
                        cursor?: components["schemas"]["PresenceCursor"] | null;
                        /** Selection */
                        selection?: string[];
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Ok
                             * @default true
                             */
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/data/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                    cell_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Views */
                            views: components["schemas"]["ViewRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/views/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** View Name */
                        view_name: string;
                        /** Range */
                        range: string;
                        /**
                         * Use Headers
                         * @default true
                         */
                        use_headers?: boolean;
                        /**
                         * Enable Insert
                         * @default false
                         */
                        enable_insert?: boolean;
                        /**
                         * Enable Update
                         * @default false
                         */
                        enable_update?: boolean;
                        /**
                         * Enable Delete
                         * @default false
                         */
                        enable_delete?: boolean;
                        /**
                         * Delete Mode
                         * @default clear
                         */
                        delete_mode?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            view: components["schemas"]["ViewRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/views/{view_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                    view_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Ok
                             * @default true
                             */
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Named Ranges */
                            named_ranges: components["schemas"]["NamedRangeRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/names/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Name */
                        name: string;
                        /** Definition */
                        definition: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            named_range: components["schemas"]["NamedRangeRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/names/{name}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Ok
                             * @default true
                             */
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/dropdown-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Dropdown Rules */
                            dropdown_rules: components["schemas"]["DropdownRuleRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/dropdown-rules/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Name
                         * @default null
                         */
                        name?: string | null;
                        /**
                         * Multi
                         * @default false
                         */
                        multi?: boolean;
                        /** Options */
                        options?: components["schemas"]["DropdownOptionRecord"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dropdown_rule: components["schemas"]["DropdownRuleRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/dropdown-rules/{rule_id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    rule_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Name Set
                         * @default false
                         */
                        name_set?: boolean;
                        /**
                         * Name
                         * @default null
                         */
                        name?: string | null;
                        /**
                         * Multi
                         * @default null
                         */
                        multi?: boolean | null;
                        /**
                         * Options
                         * @default null
                         */
                        options?: components["schemas"]["DropdownOptionRecord"][] | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dropdown_rule: components["schemas"]["DropdownRuleRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/dropdown-rules/{rule_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    rule_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Ok
                             * @default true
                             */
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default null */
                            filter: components["schemas"]["FilterRecord"] | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/filter/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Range */
                        range: string;
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            filter: components["schemas"]["FilterRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/filter/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Set Predicate
                         * @default false
                         */
                        set_predicate?: boolean;
                        /**
                         * Predicate Col Idx
                         * @default null
                         */
                        predicate_col_idx?: number | null;
                        /**
                         * Predicate Hidden
                         * @default null
                         */
                        predicate_hidden?: string[] | null;
                        /**
                         * Set Sort
                         * @default false
                         */
                        set_sort?: boolean;
                        /**
                         * Sort Col Idx
                         * @default null
                         */
                        sort_col_idx?: number | null;
                        /**
                         * Sort Direction
                         * @default null
                         */
                        sort_direction?: ("asc" | "desc") | null;
                        /**
                         * Client Id
                         * @default null
                         */
                        client_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            filter: components["schemas"]["FilterRecord"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{database}/-/sheets/api/workbooks/{workbook_id}/sheets/{sheet_id}/filter/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    database: string;
                    workbook_id: string;
                    sheet_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Ok
                             * @default true
                             */
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** WorkbookRecord */
        WorkbookRecord: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** SheetRecord */
        SheetRecord: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Sort Order */
            sort_order: number;
        };
        /** ColumnRecord */
        ColumnRecord: {
            /** Col Idx */
            col_idx: number;
            /** Name */
            name: string;
            /** Width */
            width: number;
        };
        /** CellRecord */
        CellRecord: {
            /** Row Idx */
            row_idx: number;
            /** Col Idx */
            col_idx: number;
            /** Raw Value */
            raw_value: string;
            /**
             * Format Json
             * @default null
             */
            format_json: string | null;
            /**
             * Typed Kind
             * @default null
             */
            typed_kind: string | null;
        };
        /** CellChangeBody */
        CellChangeBody: {
            /** Row Idx */
            row_idx: number;
            /** Col Idx */
            col_idx: number;
            /**
             * Raw Value
             * @default
             */
            raw_value: string;
            /**
             * Format Json
             * @default null
             */
            format_json: string | null;
            /**
             * Kind
             * @default raw
             * @enum {string}
             */
            kind: "raw" | "string";
        };
        /** ColumnChangeBody */
        ColumnChangeBody: {
            /** Col Idx */
            col_idx: number;
            /**
             * Name
             * @default null
             */
            name: string | null;
            /**
             * Width
             * @default null
             */
            width: number | null;
        };
        /** MoveColumnsResult */
        MoveColumnsResult: {
            /** Src Start */
            src_start: number;
            /** Src End */
            src_end: number;
            /** Final Start */
            final_start: number;
            /** Width */
            width: number;
        };
        /** MoveRowsResult */
        MoveRowsResult: {
            /** Src Start */
            src_start: number;
            /** Src End */
            src_end: number;
            /** Final Start */
            final_start: number;
            /** Width */
            width: number;
        };
        /** PresenceCursor */
        PresenceCursor: {
            /** Row */
            row: number;
            /** Col */
            col: number;
        };
        /** ViewRecord */
        ViewRecord: {
            /** Id */
            id: string;
            /** View Name */
            view_name: string;
            /** Range Str */
            range_str: string;
            /** Min Row */
            min_row: number;
            /** Min Col */
            min_col: number;
            /** Max Row */
            max_row: number;
            /** Max Col */
            max_col: number;
            /** Use Headers */
            use_headers: boolean;
            /** Color */
            color: string;
            /** Enable Insert */
            enable_insert: boolean;
            /** Enable Update */
            enable_update: boolean;
            /** Enable Delete */
            enable_delete: boolean;
            /** Delete Mode */
            delete_mode: string;
        };
        /** NamedRangeRecord */
        NamedRangeRecord: {
            /** Name */
            name: string;
            /** Definition */
            definition: string;
            /** Updated At */
            updated_at: string;
        };
        /** DropdownOptionRecord */
        DropdownOptionRecord: {
            /** Value */
            value: string;
            /** Color */
            color: string;
        };
        /** DropdownRuleRecord */
        DropdownRuleRecord: {
            /** Id */
            id: string;
            /**
             * Name
             * @default null
             */
            name: string | null;
            /** Multi */
            multi: boolean;
            source: components["schemas"]["DropdownRuleSource"];
        };
        /**
         * DropdownRuleSource
         * @description Discriminated source — only ``kind: "list"`` for v1, but the
         *     wrapper keeps room for ``"range"`` later without rename.
         */
        DropdownRuleSource: {
            /**
             * Kind
             * @default list
             */
            kind: string;
            /** Options */
            options?: components["schemas"]["DropdownOptionRecord"][];
        };
        /** FilterPredicate */
        FilterPredicate: {
            /** Hidden */
            hidden?: string[];
        };
        /** FilterRecord */
        FilterRecord: {
            /** Id */
            id: string;
            /** Min Row */
            min_row: number;
            /** Min Col */
            min_col: number;
            /** Max Row */
            max_row: number;
            /** Max Col */
            max_col: number;
            /**
             * Sort Col Idx
             * @default null
             */
            sort_col_idx: number | null;
            /**
             * Sort Direction
             * @default null
             */
            sort_direction: ("asc" | "desc") | null;
            /** Predicates */
            predicates?: {
                [key: string]: components["schemas"]["FilterPredicate"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
