"""AUTOGENERATED by tools/gen_queries.py — do not edit.

Regenerate with `just codegen-queries` after editing
datasette_sheets/sql/queries.sql.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Any


@dataclass
class Workbook:
    id: str
    name: str
    created_at: str
    updated_at: str
    created_by: str | None
    sort_order: int


@dataclass
class Sheet:
    id: str
    workbook_id: str
    name: str
    color: str
    sort_order: int
    created_at: str
    updated_at: str


@dataclass
class Column:
    sheet_id: str
    col_idx: int
    name: str
    width: int
    format_json: str | None


@dataclass
class Cell:
    sheet_id: str
    row_idx: int
    col_idx: int
    raw_value: str
    computed_value: Any
    computed_value_kind: str | None
    typed_kind: str | None
    typed_data: str | None
    format_json: str | None
    updated_at: str
    updated_by: str | None


@dataclass
class ListCellsForRecalcRow:
    row_idx: int
    col_idx: int
    raw_value: str
    typed_kind: str | None
    typed_data: str | None
    computed_value: Any
    computed_value_kind: str | None


@dataclass
class ListNamedRangesForRecalcRow:
    name: str
    definition: str


@dataclass
class ListFormulaCellsRow:
    row_idx: int
    col_idx: int
    raw_value: str


@dataclass
class NamedRange:
    sheet_id: str
    name: str
    definition: str
    updated_at: str


@dataclass
class DeleteNamedRangeRow:
    name: str


@dataclass
class DropdownRule:
    id: str
    workbook_id: str
    name: str | None
    multi: int
    options_json: str
    updated_at: str


@dataclass
class DeleteDropdownRuleRow:
    id: str


@dataclass
class View:
    id: str
    sheet_id: str
    view_name: str
    range_str: str
    min_row: int
    min_col: int
    max_row: int
    max_col: int
    use_headers: int
    color: str
    created_at: str
    enable_insert: int
    enable_update: int
    enable_delete: int
    delete_mode: str


@dataclass
class ListCellsInRowRow:
    col_idx: int
    computed_value: Any


@dataclass
class Filter:
    id: str
    sheet_id: str
    min_row: int
    min_col: int
    max_row: int
    max_col: int
    sort_col_idx: int | None
    sort_direction: str | None
    predicates_json: str
    created_at: str
    updated_at: str


@dataclass
class ListCellsInColRangeRow:
    row_idx: int
    computed_value: Any
    computed_value_kind: str | None


def list_workbooks(conn: sqlite3.Connection) -> list[Workbook]:
    sql = """\
select
    id,
    name,
    created_at,
    updated_at,
    created_by,
    sort_order
from datasette_sheets_workbook
order by sort_order, created_at;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [Workbook(*row) for row in cursor.fetchall()]


def get_workbook(conn: sqlite3.Connection, workbook_id: str) -> Workbook | None:
    sql = """\
select
    id,
    name,
    created_at,
    updated_at,
    created_by,
    sort_order
from datasette_sheets_workbook
where id = $workbook_id::text;
"""
    params = {"workbook_id::text": workbook_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Workbook(*row) if row is not None else None


def insert_workbook(
    conn: sqlite3.Connection, workbook_id: str, name: str, created_by: str | None
) -> Workbook | None:
    sql = """\
insert into datasette_sheets_workbook (id, name, created_by)
values ($workbook_id::text, $name::text, $created_by::text::)
returning id, name, created_at, updated_at, created_by, sort_order;
"""
    params = {
        "workbook_id::text": workbook_id,
        "name::text": name,
        "created_by::text::": created_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Workbook(*row) if row is not None else None


def update_workbook(
    conn: sqlite3.Connection,
    name_do_update: bool,
    name: str,
    sort_order_do_update: bool,
    sort_order: int,
    workbook_id: str,
) -> Workbook | None:
    sql = """\
update datasette_sheets_workbook
set name = case when $name_do_update::boolean then $name::text else name end,
    sort_order = case
        when $sort_order_do_update::boolean then $sort_order::integer
        else sort_order
    end,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $workbook_id::text
returning id, name, created_at, updated_at, created_by, sort_order;
"""
    params = {
        "name_do_update::boolean": name_do_update,
        "name::text": name,
        "sort_order_do_update::boolean": sort_order_do_update,
        "sort_order::integer": sort_order,
        "workbook_id::text": workbook_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Workbook(*row) if row is not None else None


def delete_workbook_cells(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = """\
delete from datasette_sheets_cell
where sheet_id in (
    select id from datasette_sheets_sheet where workbook_id = $workbook_id::text
);
"""
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def delete_workbook_columns(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = """\
delete from datasette_sheets_column
where sheet_id in (
    select id from datasette_sheets_sheet where workbook_id = $workbook_id::text
);
"""
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def delete_workbook_named_ranges(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = """\
delete from datasette_sheets_named_range
where sheet_id in (
    select id from datasette_sheets_sheet where workbook_id = $workbook_id::text
);
"""
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def delete_workbook_sheets(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = "delete from datasette_sheets_sheet where workbook_id = $workbook_id::text;"
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def delete_workbook_row(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = "delete from datasette_sheets_workbook where id = $workbook_id::text;"
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def list_sheets(conn: sqlite3.Connection, workbook_id: str) -> list[Sheet]:
    sql = """\
select id, workbook_id, name, color, sort_order, created_at, updated_at
from datasette_sheets_sheet
where workbook_id = $workbook_id::text
order by sort_order, created_at;
"""
    params = {"workbook_id::text": workbook_id}
    cursor = conn.execute(sql, params)
    return [Sheet(*row) for row in cursor.fetchall()]


def get_sheet(conn: sqlite3.Connection, sheet_id: str) -> Sheet | None:
    sql = """\
select id, workbook_id, name, color, sort_order, created_at, updated_at
from datasette_sheets_sheet
where id = $sheet_id::text;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Sheet(*row) if row is not None else None


def insert_sheet(
    conn: sqlite3.Connection, sheet_id: str, workbook_id: str, name: str, color: str
) -> Sheet | None:
    sql = """\
insert into datasette_sheets_sheet (id, workbook_id, name, color)
values ($sheet_id::text, $workbook_id::text, $name::text, $color::text)
returning id, workbook_id, name, color, sort_order, created_at, updated_at;
"""
    params = {
        "sheet_id::text": sheet_id,
        "workbook_id::text": workbook_id,
        "name::text": name,
        "color::text": color,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Sheet(*row) if row is not None else None


def update_sheet(
    conn: sqlite3.Connection,
    name_do_update: bool,
    name: str,
    color_do_update: bool,
    color: str,
    sort_order_do_update: bool,
    sort_order: int,
    sheet_id: str,
) -> Sheet | None:
    sql = """\
update datasette_sheets_sheet
set name = case when $name_do_update::boolean then $name::text else name end,
    color = case when $color_do_update::boolean then $color::text else color end,
    sort_order = case
        when $sort_order_do_update::boolean then $sort_order::integer
        else sort_order
    end,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $sheet_id::text
returning id, workbook_id, name, color, sort_order, created_at, updated_at;
"""
    params = {
        "name_do_update::boolean": name_do_update,
        "name::text": name,
        "color_do_update::boolean": color_do_update,
        "color::text": color,
        "sort_order_do_update::boolean": sort_order_do_update,
        "sort_order::integer": sort_order,
        "sheet_id::text": sheet_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Sheet(*row) if row is not None else None


def insert_default_column(
    conn: sqlite3.Connection, sheet_id: str, col_idx: int, name: str, width: int
) -> None:
    sql = """\
insert into datasette_sheets_column (sheet_id, col_idx, name, width)
values ($sheet_id::text, $col_idx::integer, $name::text, $width::integer);
"""
    params = {
        "sheet_id::text": sheet_id,
        "col_idx::integer": col_idx,
        "name::text": name,
        "width::integer": width,
    }
    conn.execute(sql, params)
    return None


def delete_sheet_cells(conn: sqlite3.Connection, sheet_id: str) -> None:
    sql = "delete from datasette_sheets_cell where sheet_id = $sheet_id::text;"
    params = {"sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def delete_sheet_columns(conn: sqlite3.Connection, sheet_id: str) -> None:
    sql = "delete from datasette_sheets_column where sheet_id = $sheet_id::text;"
    params = {"sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def delete_sheet_named_ranges(conn: sqlite3.Connection, sheet_id: str) -> None:
    sql = "delete from datasette_sheets_named_range where sheet_id = $sheet_id::text;"
    params = {"sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def delete_sheet_row(conn: sqlite3.Connection, sheet_id: str) -> None:
    sql = "delete from datasette_sheets_sheet where id = $sheet_id::text;"
    params = {"sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def reorder_sheet(
    conn: sqlite3.Connection, sort_order: int, sheet_id: str, workbook_id: str
) -> None:
    sql = """\
update datasette_sheets_sheet
set sort_order = $sort_order::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $sheet_id::text
  and workbook_id = $workbook_id::text;
"""
    params = {
        "sort_order::integer": sort_order,
        "sheet_id::text": sheet_id,
        "workbook_id::text": workbook_id,
    }
    conn.execute(sql, params)
    return None


def touch_sheet(conn: sqlite3.Connection, sheet_id: str) -> None:
    sql = """\
update datasette_sheets_sheet
set updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $sheet_id::text;
"""
    params = {"sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def list_columns(conn: sqlite3.Connection, sheet_id: str) -> list[Column]:
    sql = """\
select sheet_id, col_idx, name, width, format_json
from datasette_sheets_column
where sheet_id = $sheet_id::text
order by col_idx;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [Column(*row) for row in cursor.fetchall()]


def set_column(
    conn: sqlite3.Connection,
    name_do_update: bool,
    name: str,
    width_do_update: bool,
    width: int,
    sheet_id: str,
    col_idx: int,
) -> Column | None:
    sql = """\
update datasette_sheets_column
set name = case when $name_do_update::boolean then $name::text else name end,
    width = case
        when $width_do_update::boolean then $width::integer
        else width
    end
where sheet_id = $sheet_id::text
  and col_idx = $col_idx::integer
returning sheet_id, col_idx, name, width, format_json;
"""
    params = {
        "name_do_update::boolean": name_do_update,
        "name::text": name,
        "width_do_update::boolean": width_do_update,
        "width::integer": width,
        "sheet_id::text": sheet_id,
        "col_idx::integer": col_idx,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Column(*row) if row is not None else None


def list_cells(conn: sqlite3.Connection, sheet_id: str) -> list[Cell]:
    sql = """\
select sheet_id, row_idx, col_idx, raw_value, computed_value,
       computed_value_kind, typed_kind, typed_data, format_json,
       updated_at, updated_by
from datasette_sheets_cell
where sheet_id = $sheet_id::text
order by row_idx, col_idx;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [Cell(*row) for row in cursor.fetchall()]


def delete_cell(
    conn: sqlite3.Connection, sheet_id: str, row_idx: int, col_idx: int
) -> None:
    sql = """\
delete from datasette_sheets_cell
where sheet_id = $sheet_id::text
  and row_idx = $row_idx::integer
  and col_idx = $col_idx::integer;
"""
    params = {
        "sheet_id::text": sheet_id,
        "row_idx::integer": row_idx,
        "col_idx::integer": col_idx,
    }
    conn.execute(sql, params)
    return None


def upsert_cell(
    conn: sqlite3.Connection,
    sheet_id: str,
    row_idx: int,
    col_idx: int,
    raw_value: str,
    format_json: str | None,
    typed_kind: str | None,
    typed_data: str | None,
    updated_by: str | None,
) -> None:
    sql = """\
insert into datasette_sheets_cell
    (sheet_id, row_idx, col_idx, raw_value, format_json,
     typed_kind, typed_data, updated_by, updated_at)
values
    ($sheet_id::text, $row_idx::integer, $col_idx::integer,
     $raw_value::text, $format_json::text::,
     $typed_kind::text::, $typed_data::text::,
     $updated_by::text::, strftime('%Y-%m-%dT%H:%M:%f', 'now'))
on conflict(sheet_id, row_idx, col_idx) do update set
    raw_value = excluded.raw_value,
    format_json = excluded.format_json,
    typed_kind = excluded.typed_kind,
    typed_data = excluded.typed_data,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at;
"""
    params = {
        "sheet_id::text": sheet_id,
        "row_idx::integer": row_idx,
        "col_idx::integer": col_idx,
        "raw_value::text": raw_value,
        "format_json::text::": format_json,
        "typed_kind::text::": typed_kind,
        "typed_data::text::": typed_data,
        "updated_by::text::": updated_by,
    }
    conn.execute(sql, params)
    return None


def list_cells_for_recalc(
    conn: sqlite3.Connection, sheet_id: str
) -> list[ListCellsForRecalcRow]:
    sql = """\
select row_idx, col_idx, raw_value, typed_kind, typed_data,
       computed_value, computed_value_kind
from datasette_sheets_cell
where sheet_id = $sheet_id::text;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [ListCellsForRecalcRow(*row) for row in cursor.fetchall()]


def list_named_ranges_for_recalc(
    conn: sqlite3.Connection, sheet_id: str
) -> list[ListNamedRangesForRecalcRow]:
    sql = """\
select name, definition
from datasette_sheets_named_range
where sheet_id = $sheet_id::text;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [ListNamedRangesForRecalcRow(*row) for row in cursor.fetchall()]


def update_cell_computed(
    conn: sqlite3.Connection,
    value: Any,
    kind: str | None,
    sheet_id: str,
    row_idx: int,
    col_idx: int,
) -> None:
    sql = """\
update datasette_sheets_cell
set computed_value = $value::,
    computed_value_kind = $kind::text::
where sheet_id = $sheet_id::text
  and row_idx = $row_idx::integer
  and col_idx = $col_idx::integer;
"""
    params = {
        "value::": value,
        "kind::text::": kind,
        "sheet_id::text": sheet_id,
        "row_idx::integer": row_idx,
        "col_idx::integer": col_idx,
    }
    conn.execute(sql, params)
    return None


def list_formula_cells(
    conn: sqlite3.Connection, sheet_id: str
) -> list[ListFormulaCellsRow]:
    sql = """\
select row_idx, col_idx, raw_value
from datasette_sheets_cell
where sheet_id = $sheet_id::text
  and raw_value like '=%';
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [ListFormulaCellsRow(*row) for row in cursor.fetchall()]


def update_cell_raw(
    conn: sqlite3.Connection, raw_value: str, sheet_id: str, row_idx: int, col_idx: int
) -> None:
    sql = """\
update datasette_sheets_cell
set raw_value = $raw_value::text
where sheet_id = $sheet_id::text
  and row_idx = $row_idx::integer
  and col_idx = $col_idx::integer;
"""
    params = {
        "raw_value::text": raw_value,
        "sheet_id::text": sheet_id,
        "row_idx::integer": row_idx,
        "col_idx::integer": col_idx,
    }
    conn.execute(sql, params)
    return None


def delete_cells_in_rows(
    conn: sqlite3.Connection, sheet_id: str, row_indices_json: str
) -> None:
    sql = """\
delete from datasette_sheets_cell
where sheet_id = $sheet_id::text
  and row_idx in (
    select cast(value as integer) from json_each($row_indices_json::text)
  );
"""
    params = {"sheet_id::text": sheet_id, "row_indices_json::text": row_indices_json}
    conn.execute(sql, params)
    return None


def shift_cell_rows_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, row_indices_json: str
) -> None:
    sql = """\
update datasette_sheets_cell
set row_idx = -(row_idx + 1)
where sheet_id = $sheet_id::text
  and row_idx > (
    select min(cast(value as integer)) from json_each($row_indices_json::text)
  );
"""
    params = {"sheet_id::text": sheet_id, "row_indices_json::text": row_indices_json}
    conn.execute(sql, params)
    return None


def shift_cell_rows_from_buffer(
    conn: sqlite3.Connection, row_indices_json: str, sheet_id: str
) -> None:
    sql = """\
update datasette_sheets_cell
set row_idx = (-row_idx - 1) - (
    select count(*) from json_each($row_indices_json::text)
    where cast(value as integer) < (-datasette_sheets_cell.row_idx - 1)
)
where sheet_id = $sheet_id::text
  and row_idx < 0;
"""
    params = {"row_indices_json::text": row_indices_json, "sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def delete_cells_in_cols(
    conn: sqlite3.Connection, sheet_id: str, col_indices_json: str
) -> None:
    sql = """\
delete from datasette_sheets_cell
where sheet_id = $sheet_id::text
  and col_idx in (
    select cast(value as integer) from json_each($col_indices_json::text)
  );
"""
    params = {"sheet_id::text": sheet_id, "col_indices_json::text": col_indices_json}
    conn.execute(sql, params)
    return None


def delete_columns_in_cols(
    conn: sqlite3.Connection, sheet_id: str, col_indices_json: str
) -> None:
    sql = """\
delete from datasette_sheets_column
where sheet_id = $sheet_id::text
  and col_idx in (
    select cast(value as integer) from json_each($col_indices_json::text)
  );
"""
    params = {"sheet_id::text": sheet_id, "col_indices_json::text": col_indices_json}
    conn.execute(sql, params)
    return None


def shift_cell_cols_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, col_indices_json: str
) -> None:
    sql = """\
update datasette_sheets_cell
set col_idx = -(col_idx + 1)
where sheet_id = $sheet_id::text
  and col_idx > (
    select min(cast(value as integer)) from json_each($col_indices_json::text)
  );
"""
    params = {"sheet_id::text": sheet_id, "col_indices_json::text": col_indices_json}
    conn.execute(sql, params)
    return None


def shift_cell_cols_from_buffer(
    conn: sqlite3.Connection, col_indices_json: str, sheet_id: str
) -> None:
    sql = """\
update datasette_sheets_cell
set col_idx = (-col_idx - 1) - (
    select count(*) from json_each($col_indices_json::text)
    where cast(value as integer) < (-datasette_sheets_cell.col_idx - 1)
)
where sheet_id = $sheet_id::text
  and col_idx < 0;
"""
    params = {"col_indices_json::text": col_indices_json, "sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def shift_column_cols_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, col_indices_json: str
) -> None:
    sql = """\
update datasette_sheets_column
set col_idx = -(col_idx + 1)
where sheet_id = $sheet_id::text
  and col_idx > (
    select min(cast(value as integer)) from json_each($col_indices_json::text)
  );
"""
    params = {"sheet_id::text": sheet_id, "col_indices_json::text": col_indices_json}
    conn.execute(sql, params)
    return None


def shift_column_cols_from_buffer(
    conn: sqlite3.Connection, col_indices_json: str, sheet_id: str
) -> None:
    sql = """\
update datasette_sheets_column
set col_idx = (-col_idx - 1) - (
    select count(*) from json_each($col_indices_json::text)
    where cast(value as integer) < (-datasette_sheets_column.col_idx - 1)
)
where sheet_id = $sheet_id::text
  and col_idx < 0;
"""
    params = {"col_indices_json::text": col_indices_json, "sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def insert_shift_cell_cols_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, at: int
) -> None:
    sql = """\
update datasette_sheets_cell
set col_idx = -(col_idx + 1)
where sheet_id = $sheet_id::text
  and col_idx >= $at::integer;
"""
    params = {"sheet_id::text": sheet_id, "at::integer": at}
    conn.execute(sql, params)
    return None


def insert_shift_cell_cols_from_buffer(
    conn: sqlite3.Connection, count: int, sheet_id: str
) -> None:
    sql = """\
update datasette_sheets_cell
set col_idx = (-col_idx - 1) + $count::integer
where sheet_id = $sheet_id::text
  and col_idx < 0;
"""
    params = {"count::integer": count, "sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def insert_shift_column_cols_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, at: int
) -> None:
    sql = """\
update datasette_sheets_column
set col_idx = -(col_idx + 1)
where sheet_id = $sheet_id::text
  and col_idx >= $at::integer;
"""
    params = {"sheet_id::text": sheet_id, "at::integer": at}
    conn.execute(sql, params)
    return None


def insert_shift_column_cols_from_buffer(
    conn: sqlite3.Connection, count: int, sheet_id: str
) -> None:
    sql = """\
update datasette_sheets_column
set col_idx = (-col_idx - 1) + $count::integer
where sheet_id = $sheet_id::text
  and col_idx < 0;
"""
    params = {"count::integer": count, "sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def move_cell_cols_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, low: int, high: int
) -> None:
    sql = """\
update datasette_sheets_cell
set col_idx = -(col_idx + 1)
where sheet_id = $sheet_id::text
  and col_idx between $low::integer and $high::integer;
"""
    params = {"sheet_id::text": sheet_id, "low::integer": low, "high::integer": high}
    conn.execute(sql, params)
    return None


def move_cell_cols_from_buffer(
    conn: sqlite3.Connection,
    src_start: int,
    src_end: int,
    final_start: int,
    width: int,
    sheet_id: str,
) -> None:
    sql = """\
update datasette_sheets_cell
set col_idx = case
  when (-col_idx - 1) between $src_start::integer and $src_end::integer
    then (-col_idx - 1) - $src_start::integer + $final_start::integer
  when (-col_idx - 1) < $src_start::integer
    then (-col_idx - 1) + $width::integer
  else (-col_idx - 1) - $width::integer
end
where sheet_id = $sheet_id::text
  and col_idx < 0;
"""
    params = {
        "src_start::integer": src_start,
        "src_end::integer": src_end,
        "final_start::integer": final_start,
        "width::integer": width,
        "sheet_id::text": sheet_id,
    }
    conn.execute(sql, params)
    return None


def move_column_meta_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, low: int, high: int
) -> None:
    sql = """\
update datasette_sheets_column
set col_idx = -(col_idx + 1)
where sheet_id = $sheet_id::text
  and col_idx between $low::integer and $high::integer;
"""
    params = {"sheet_id::text": sheet_id, "low::integer": low, "high::integer": high}
    conn.execute(sql, params)
    return None


def move_column_meta_from_buffer(
    conn: sqlite3.Connection,
    src_start: int,
    src_end: int,
    final_start: int,
    width: int,
    sheet_id: str,
) -> None:
    sql = """\
update datasette_sheets_column
set col_idx = case
  when (-col_idx - 1) between $src_start::integer and $src_end::integer
    then (-col_idx - 1) - $src_start::integer + $final_start::integer
  when (-col_idx - 1) < $src_start::integer
    then (-col_idx - 1) + $width::integer
  else (-col_idx - 1) - $width::integer
end
where sheet_id = $sheet_id::text
  and col_idx < 0;
"""
    params = {
        "src_start::integer": src_start,
        "src_end::integer": src_end,
        "final_start::integer": final_start,
        "width::integer": width,
        "sheet_id::text": sheet_id,
    }
    conn.execute(sql, params)
    return None


def move_cell_rows_to_buffer(
    conn: sqlite3.Connection, sheet_id: str, low: int, high: int
) -> None:
    sql = """\
update datasette_sheets_cell
set row_idx = -(row_idx + 1)
where sheet_id = $sheet_id::text
  and row_idx between $low::integer and $high::integer;
"""
    params = {"sheet_id::text": sheet_id, "low::integer": low, "high::integer": high}
    conn.execute(sql, params)
    return None


def move_cell_rows_from_buffer(
    conn: sqlite3.Connection,
    src_start: int,
    src_end: int,
    final_start: int,
    width: int,
    sheet_id: str,
) -> None:
    sql = """\
update datasette_sheets_cell
set row_idx = case
  when (-row_idx - 1) between $src_start::integer and $src_end::integer
    then (-row_idx - 1) - $src_start::integer + $final_start::integer
  when (-row_idx - 1) < $src_start::integer
    then (-row_idx - 1) + $width::integer
  else (-row_idx - 1) - $width::integer
end
where sheet_id = $sheet_id::text
  and row_idx < 0;
"""
    params = {
        "src_start::integer": src_start,
        "src_end::integer": src_end,
        "final_start::integer": final_start,
        "width::integer": width,
        "sheet_id::text": sheet_id,
    }
    conn.execute(sql, params)
    return None


def list_named_ranges(conn: sqlite3.Connection, sheet_id: str) -> list[NamedRange]:
    sql = """\
select sheet_id, name, definition, updated_at
from datasette_sheets_named_range
where sheet_id = $sheet_id::text
order by name collate nocase;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [NamedRange(*row) for row in cursor.fetchall()]


def upsert_named_range(
    conn: sqlite3.Connection, sheet_id: str, name: str, definition: str
) -> NamedRange | None:
    sql = """\
insert into datasette_sheets_named_range
    (sheet_id, name, definition, updated_at)
values
    ($sheet_id::text, $name::text, $definition::text,
     strftime('%Y-%m-%dT%H:%M:%f', 'now'))
on conflict(sheet_id, name) do update set
    definition = excluded.definition,
    updated_at = excluded.updated_at
returning sheet_id, name, definition, updated_at;
"""
    params = {
        "sheet_id::text": sheet_id,
        "name::text": name,
        "definition::text": definition,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return NamedRange(*row) if row is not None else None


def delete_named_range(
    conn: sqlite3.Connection, sheet_id: str, name: str
) -> DeleteNamedRangeRow | None:
    sql = """\
delete from datasette_sheets_named_range
where sheet_id = $sheet_id::text
  and name = $name::text collate nocase
returning name;
"""
    params = {"sheet_id::text": sheet_id, "name::text": name}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return DeleteNamedRangeRow(*row) if row is not None else None


def update_named_range_definition(
    conn: sqlite3.Connection, definition: str, sheet_id: str, name: str
) -> None:
    sql = """\
update datasette_sheets_named_range
set definition = $definition::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where sheet_id = $sheet_id::text
  and name = $name::text collate nocase;
"""
    params = {
        "definition::text": definition,
        "sheet_id::text": sheet_id,
        "name::text": name,
    }
    conn.execute(sql, params)
    return None


def list_dropdown_rules(
    conn: sqlite3.Connection, workbook_id: str
) -> list[DropdownRule]:
    sql = """\
select id, workbook_id, name, multi, options_json, updated_at
from datasette_sheets_dropdown_rule
where workbook_id = $workbook_id::text
order by coalesce(name, ''), id;
"""
    params = {"workbook_id::text": workbook_id}
    cursor = conn.execute(sql, params)
    return [DropdownRule(*row) for row in cursor.fetchall()]


def get_dropdown_rule(
    conn: sqlite3.Connection, rule_id: str, workbook_id: str
) -> DropdownRule | None:
    sql = """\
select id, workbook_id, name, multi, options_json, updated_at
from datasette_sheets_dropdown_rule
where id = $rule_id::text
  and workbook_id = $workbook_id::text;
"""
    params = {"rule_id::text": rule_id, "workbook_id::text": workbook_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return DropdownRule(*row) if row is not None else None


def insert_dropdown_rule(
    conn: sqlite3.Connection,
    rule_id: str,
    workbook_id: str,
    name: str | None,
    multi: int,
    options_json: str,
) -> DropdownRule | None:
    sql = """\
insert into datasette_sheets_dropdown_rule
    (id, workbook_id, name, multi, options_json, updated_at)
values
    ($rule_id::text, $workbook_id::text, $name::text::,
     $multi::integer, $options_json::text,
     strftime('%Y-%m-%dT%H:%M:%f', 'now'))
returning id, workbook_id, name, multi, options_json, updated_at;
"""
    params = {
        "rule_id::text": rule_id,
        "workbook_id::text": workbook_id,
        "name::text::": name,
        "multi::integer": multi,
        "options_json::text": options_json,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return DropdownRule(*row) if row is not None else None


def update_dropdown_rule(
    conn: sqlite3.Connection,
    name_do_update: bool,
    name: str | None,
    multi_do_update: bool,
    multi: int,
    options_do_update: bool,
    options_json: str,
    rule_id: str,
    workbook_id: str,
) -> DropdownRule | None:
    sql = """\
update datasette_sheets_dropdown_rule
set name = case
        when $name_do_update::boolean then $name::text::
        else name
    end,
    multi = case
        when $multi_do_update::boolean then $multi::integer
        else multi
    end,
    options_json = case
        when $options_do_update::boolean then $options_json::text
        else options_json
    end,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $rule_id::text
  and workbook_id = $workbook_id::text
returning id, workbook_id, name, multi, options_json, updated_at;
"""
    params = {
        "name_do_update::boolean": name_do_update,
        "name::text::": name,
        "multi_do_update::boolean": multi_do_update,
        "multi::integer": multi,
        "options_do_update::boolean": options_do_update,
        "options_json::text": options_json,
        "rule_id::text": rule_id,
        "workbook_id::text": workbook_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return DropdownRule(*row) if row is not None else None


def delete_dropdown_rule(
    conn: sqlite3.Connection, rule_id: str, workbook_id: str
) -> DeleteDropdownRuleRow | None:
    sql = """\
delete from datasette_sheets_dropdown_rule
where id = $rule_id::text
  and workbook_id = $workbook_id::text
returning id;
"""
    params = {"rule_id::text": rule_id, "workbook_id::text": workbook_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return DeleteDropdownRuleRow(*row) if row is not None else None


def delete_workbook_dropdown_rules(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = """\
delete from datasette_sheets_dropdown_rule
where workbook_id = $workbook_id::text;
"""
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def list_views(conn: sqlite3.Connection, sheet_id: str) -> list[View]:
    sql = """\
select id, sheet_id, view_name, range_str, min_row, min_col, max_row, max_col,
       use_headers, color, created_at, enable_insert, enable_update,
       enable_delete, delete_mode
from datasette_sheets_view
where sheet_id = $sheet_id::text
order by created_at;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    return [View(*row) for row in cursor.fetchall()]


def get_view(conn: sqlite3.Connection, view_id: str) -> View | None:
    sql = """\
select id, sheet_id, view_name, range_str, min_row, min_col, max_row, max_col,
       use_headers, color, created_at, enable_insert, enable_update,
       enable_delete, delete_mode
from datasette_sheets_view
where id = $view_id::text;
"""
    params = {"view_id::text": view_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return View(*row) if row is not None else None


def insert_view(
    conn: sqlite3.Connection,
    view_id: str,
    sheet_id: str,
    view_name: str,
    range_str: str,
    min_row: int,
    min_col: int,
    max_row: int,
    max_col: int,
    use_headers: int,
    color: str,
    enable_insert: int,
    enable_update: int,
    enable_delete: int,
    delete_mode: str,
) -> View | None:
    sql = """\
insert into datasette_sheets_view
    (id, sheet_id, view_name, range_str, min_row, min_col, max_row, max_col,
     use_headers, color, enable_insert, enable_update, enable_delete, delete_mode)
values
    ($view_id::text, $sheet_id::text, $view_name::text, $range_str::text,
     $min_row::integer, $min_col::integer, $max_row::integer, $max_col::integer,
     $use_headers::integer, $color::text,
     $enable_insert::integer, $enable_update::integer, $enable_delete::integer,
     $delete_mode::text)
returning id, sheet_id, view_name, range_str, min_row, min_col, max_row, max_col,
          use_headers, color, created_at, enable_insert, enable_update,
          enable_delete, delete_mode;
"""
    params = {
        "view_id::text": view_id,
        "sheet_id::text": sheet_id,
        "view_name::text": view_name,
        "range_str::text": range_str,
        "min_row::integer": min_row,
        "min_col::integer": min_col,
        "max_row::integer": max_row,
        "max_col::integer": max_col,
        "use_headers::integer": use_headers,
        "color::text": color,
        "enable_insert::integer": enable_insert,
        "enable_update::integer": enable_update,
        "enable_delete::integer": enable_delete,
        "delete_mode::text": delete_mode,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return View(*row) if row is not None else None


def delete_view(conn: sqlite3.Connection, view_id: str) -> None:
    sql = "delete from datasette_sheets_view where id = $view_id::text;"
    params = {"view_id::text": view_id}
    conn.execute(sql, params)
    return None


def update_view_col_bounds(
    conn: sqlite3.Connection, min_col: int, max_col: int, view_id: str
) -> None:
    sql = """\
update datasette_sheets_view
set min_col = $min_col::integer,
    max_col = $max_col::integer
where id = $view_id::text;
"""
    params = {
        "min_col::integer": min_col,
        "max_col::integer": max_col,
        "view_id::text": view_id,
    }
    conn.execute(sql, params)
    return None


def update_view_row_bounds(
    conn: sqlite3.Connection, min_row: int, max_row: int, view_id: str
) -> None:
    sql = """\
update datasette_sheets_view
set min_row = $min_row::integer,
    max_row = $max_row::integer
where id = $view_id::text;
"""
    params = {
        "min_row::integer": min_row,
        "max_row::integer": max_row,
        "view_id::text": view_id,
    }
    conn.execute(sql, params)
    return None


def check_name_exists(conn: sqlite3.Connection, name: str) -> str | None:
    sql = """\
select name from sqlite_master
where type in ('table', 'view') and name = $name::text;
"""
    params = {"name::text": name}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def list_cells_in_row(
    conn: sqlite3.Connection, sheet_id: str, row_idx: int, min_col: int, max_col: int
) -> list[ListCellsInRowRow]:
    sql = """\
select col_idx, computed_value
from datasette_sheets_cell
where sheet_id = $sheet_id::text
  and row_idx = $row_idx::integer
  and col_idx between $min_col::integer and $max_col::integer;
"""
    params = {
        "sheet_id::text": sheet_id,
        "row_idx::integer": row_idx,
        "min_col::integer": min_col,
        "max_col::integer": max_col,
    }
    cursor = conn.execute(sql, params)
    return [ListCellsInRowRow(*row) for row in cursor.fetchall()]


def get_filter_by_sheet(conn: sqlite3.Connection, sheet_id: str) -> Filter | None:
    sql = """\
select id, sheet_id, min_row, min_col, max_row, max_col,
       sort_col_idx, sort_direction, predicates_json,
       created_at, updated_at
from datasette_sheets_filter
where sheet_id = $sheet_id::text;
"""
    params = {"sheet_id::text": sheet_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Filter(*row) if row is not None else None


def insert_filter(
    conn: sqlite3.Connection,
    filter_id: str,
    sheet_id: str,
    min_row: int,
    min_col: int,
    max_row: int,
    max_col: int,
    sort_col_idx: Any,
    sort_direction: Any,
    predicates_json: str,
) -> Filter | None:
    sql = """\
insert into datasette_sheets_filter
    (id, sheet_id, min_row, min_col, max_row, max_col,
     sort_col_idx, sort_direction, predicates_json)
values
    ($filter_id::text, $sheet_id::text,
     $min_row::integer, $min_col::integer,
     $max_row::integer, $max_col::integer,
     $sort_col_idx::, $sort_direction::,
     $predicates_json::text)
returning id, sheet_id, min_row, min_col, max_row, max_col,
          sort_col_idx, sort_direction, predicates_json,
          created_at, updated_at;
"""
    params = {
        "filter_id::text": filter_id,
        "sheet_id::text": sheet_id,
        "min_row::integer": min_row,
        "min_col::integer": min_col,
        "max_row::integer": max_row,
        "max_col::integer": max_col,
        "sort_col_idx::": sort_col_idx,
        "sort_direction::": sort_direction,
        "predicates_json::text": predicates_json,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Filter(*row) if row is not None else None


def update_filter_col_bounds(
    conn: sqlite3.Connection, min_col: int, max_col: int, filter_id: str
) -> None:
    sql = """\
update datasette_sheets_filter
set min_col = $min_col::integer,
    max_col = $max_col::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $filter_id::text;
"""
    params = {
        "min_col::integer": min_col,
        "max_col::integer": max_col,
        "filter_id::text": filter_id,
    }
    conn.execute(sql, params)
    return None


def update_filter_row_bounds(
    conn: sqlite3.Connection, min_row: int, max_row: int, filter_id: str
) -> None:
    sql = """\
update datasette_sheets_filter
set min_row = $min_row::integer,
    max_row = $max_row::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $filter_id::text;
"""
    params = {
        "min_row::integer": min_row,
        "max_row::integer": max_row,
        "filter_id::text": filter_id,
    }
    conn.execute(sql, params)
    return None


def update_filter_sort(
    conn: sqlite3.Connection, sort_col_idx: Any, sort_direction: Any, filter_id: str
) -> None:
    sql = """\
update datasette_sheets_filter
set sort_col_idx = $sort_col_idx::,
    sort_direction = $sort_direction::,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $filter_id::text;
"""
    params = {
        "sort_col_idx::": sort_col_idx,
        "sort_direction::": sort_direction,
        "filter_id::text": filter_id,
    }
    conn.execute(sql, params)
    return None


def update_filter_predicates(
    conn: sqlite3.Connection, predicates_json: str, filter_id: str
) -> None:
    sql = """\
update datasette_sheets_filter
set predicates_json = $predicates_json::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
where id = $filter_id::text;
"""
    params = {"predicates_json::text": predicates_json, "filter_id::text": filter_id}
    conn.execute(sql, params)
    return None


def delete_filter_by_sheet(conn: sqlite3.Connection, sheet_id: str) -> None:
    sql = "delete from datasette_sheets_filter where sheet_id = $sheet_id::text;"
    params = {"sheet_id::text": sheet_id}
    conn.execute(sql, params)
    return None


def delete_workbook_filters(conn: sqlite3.Connection, workbook_id: str) -> None:
    sql = """\
delete from datasette_sheets_filter
where sheet_id in (
    select id from datasette_sheets_sheet where workbook_id = $workbook_id::text
);
"""
    params = {"workbook_id::text": workbook_id}
    conn.execute(sql, params)
    return None


def list_cells_in_col_range(
    conn: sqlite3.Connection, sheet_id: str, col_idx: int, min_row: int, max_row: int
) -> list[ListCellsInColRangeRow]:
    sql = """\
select row_idx, computed_value, computed_value_kind
from datasette_sheets_cell
where sheet_id = $sheet_id::text
  and col_idx = $col_idx::integer
  and row_idx between $min_row::integer and $max_row::integer
order by row_idx;
"""
    params = {
        "sheet_id::text": sheet_id,
        "col_idx::integer": col_idx,
        "min_row::integer": min_row,
        "max_row::integer": max_row,
    }
    cursor = conn.execute(sql, params)
    return [ListCellsInColRangeRow(*row) for row in cursor.fetchall()]
