"""Generate datasette_sheets/_queries.py from the solite-codegen JSON IR.

Adapted from ~/projects/solite-codegen-python-sqlite3/main.py. Key
differences from the upstream generator:

- Emits module-level free functions that take ``conn`` as the first
  argument, not a ``Db`` class that owns its own sqlite3 connection —
  datasette-sheets already serializes writes through
  ``database.execute_write_fn(fn)``, so generated helpers need to slot
  into an existing closure, not open their own connection.
- No schema ``executescript`` at import time — migrations.py handles that.
- Snake-cases query names and column names on the Python side.
- Adds a ``# AUTOGENERATED — do not edit`` header with the IR path so
  `just check-queries-fresh` can produce a useful diff.

Input: path to the solite-codegen JSON (argv[1]).
Output: Python source to stdout.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal


def to_snake_case(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def to_camel_case(name: str) -> str:
    return "".join(part.capitalize() for part in to_snake_case(name).split("_"))


@dataclass
class Parameter:
    full_name: str
    name: str
    annotated_type: str | None = None
    # solite-dev's IR flags each parameter as nullable/non-null based
    # on the sigil shape: ``$foo`` / ``$foo::text`` are non-null,
    # ``$foo::`` / ``$foo::text::`` are nullable. Older IRs that don't
    # carry the field default to non-null (conservative — if you want
    # nullable, opt in via the trailing ``::``).
    nullable: bool = False


@dataclass
class Column:
    name: str
    origin_database: str | None = None
    origin_table: str | None = None
    origin_column: str | None = None
    decltype: str | None = None
    # solite-dev's IR flags each output column as nullable/non-null.
    # When absent (older IRs) or missing context (expressions, joins
    # solite can't statically prove non-null), assume nullable — it's
    # the safe side of the type lattice.
    nullable: bool = True


ResultType = Literal["Void", "Rows", "Row", "Value", "List"]


@dataclass
class Export:
    name: str
    columns: list[Column]
    parameters: list[Parameter]
    sql: str
    result_type: ResultType
    # Optional `-- name: foo :row -> Widget` hint. When two row-returning
    # queries target the same class name, the generator dedupes them
    # into a single dataclass. When absent, falls back to
    # ``<CamelName>Row`` derived from the query's own name.
    result_class: str | None = None

    @staticmethod
    def from_json(data: dict) -> "Export":
        return Export(
            name=data["name"],
            columns=[Column(**c) for c in data.get("columns", [])],
            parameters=[Parameter(**p) for p in data.get("parameters", [])],
            sql=data["sql"],
            result_type=data.get("result_type", "Void"),
            result_class=data.get("result_class"),
        )

    def row_class_name(self) -> str:
        return self.result_class or f"{to_camel_case(self.name)}Row"


def py_type_from_annotated(annotated: str | None) -> str:
    if annotated is None:
        return "Any"
    a = annotated.lower()
    if a in ("text", "str"):
        return "str"
    if a in ("int", "integer", "bigint"):
        return "int"
    if a in ("real", "float"):
        return "float"
    if a == "blob":
        return "bytes"
    if a in ("bool", "boolean"):
        # sqlc-style partial-update queries use
        # ``$x_do_update::boolean`` as a WHEN flag; sqlite3 adapts
        # Python ``bool`` to 0/1 so CASE WHEN reads it correctly.
        return "bool"
    return "Any"


def py_type_from_decltype(decltype: str | None) -> str:
    if decltype is None:
        # ``computed_value`` has no declared type (BLOB affinity,
        # holds int/float/str). Anything else that lands here is a
        # computed column solite couldn't resolve — fall back to Any.
        return "Any"
    d = decltype.upper()
    if d == "TEXT":
        return "str"
    if d in ("INT", "INTEGER", "BIGINT"):
        return "int"
    if d in ("REAL", "FLOAT"):
        return "float"
    if d == "BLOB":
        return "bytes"
    if d in ("BOOL", "BOOLEAN"):
        return "bool"
    return "Any"


def py_type_for_column(col: Column) -> str:
    """Map a Column (decltype + nullability) to a Python type."""
    base = py_type_from_decltype(col.decltype)
    # ``Any`` already covers None; don't noisy-wrap it.
    if col.nullable and base != "Any":
        return f"{base} | None"
    return base


def py_type_for_param(param: Parameter) -> str:
    """Map a Parameter (annotated_type + nullability) to a Python type."""
    base = py_type_from_annotated(param.annotated_type)
    if param.nullable and base != "Any":
        return f"{base} | None"
    return base


def _py_literal(value: str) -> str:
    # Multi-line SQL reads much better as a triple-quoted literal
    # than repr()'d with escaped newlines.
    if "\n" in value:
        if '"""' in value:
            raise ValueError(f"SQL contains triple-double-quote: {value!r}")
        return f'"""\\\n{value}\n"""'
    return repr(value)


def _func_lines(export: Export) -> list[str]:
    func_name = to_snake_case(export.name)
    params_sig: list[str] = ["conn: sqlite3.Connection"]
    for p in export.parameters:
        params_sig.append(f"{to_snake_case(p.name)}: {py_type_for_param(p)}")

    match export.result_type:
        case "Void":
            return_type = "None"
        case "Rows":
            return_type = f"list[{export.row_class_name()}]"
        case "Row":
            return_type = f"{export.row_class_name()} | None"
        case "Value":
            if not export.columns:
                return_type = "Any | None"
            else:
                # `:value` is always `T | None` because an empty
                # result set returns None regardless of column
                # nullability. Use the non-null base so we don't
                # double-wrap into `T | None | None`.
                base = py_type_from_decltype(export.columns[0].decltype)
                return_type = "Any | None" if base == "Any" else f"{base} | None"
        case "List":
            if not export.columns:
                return_type = "list[Any]"
            else:
                return_type = f"list[{py_type_for_column(export.columns[0])}]"

    lines = [f"def {func_name}({', '.join(params_sig)}) -> {return_type}:"]
    lines.append(f"    sql = {_py_literal(export.sql)}")

    if export.parameters:
        binds = ", ".join(
            # full_name strips the leading ':' or '$'/'::type' suffix
            # to match sqlite3's bind-parameter parser.
            f'"{_strip_sigil(p.full_name)}": {to_snake_case(p.name)}'
            for p in export.parameters
        )
        lines.append(f"    params = {{{binds}}}")
    else:
        lines.append("    params: dict[str, Any] = {}")

    if export.result_type == "Void":
        lines.append("    conn.execute(sql, params)")
        lines.append("    return None")
    else:
        lines.append("    cursor = conn.execute(sql, params)")

    match export.result_type:
        case "Void":
            pass
        case "Rows":
            lines.append(
                f"    return [{export.row_class_name()}(*row) for row in cursor.fetchall()]"
            )
        case "Row":
            lines.append("    row = cursor.fetchone()")
            lines.append(
                f"    return {export.row_class_name()}(*row) if row is not None else None"
            )
        case "Value":
            lines.append("    row = cursor.fetchone()")
            lines.append("    return row[0] if row is not None else None")
        case "List":
            lines.append("    return [row[0] for row in cursor.fetchall()]")

    return lines


def _strip_sigil(full_name: str) -> str:
    # sqlite3 strips only the leading sigil ':' or '$'; a '::type'
    # annotation stays in the bind key. ':foo' -> 'foo',
    # '$foo::text' -> 'foo::text'. Caller decides the Python-side
    # argument name from Parameter.name separately.
    return full_name.lstrip(":$")


def generate(report: dict) -> str:
    exports = [Export.from_json(e) for e in report.get("exports", [])]

    lines: list[str] = [
        '"""AUTOGENERATED by tools/gen_queries.py — do not edit.',
        "",
        "Regenerate with `just codegen-queries` after editing",
        "datasette_sheets/sql/queries.sql.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import sqlite3",
        "from dataclasses import dataclass",
        "from typing import Any",
        "",
    ]

    # Emit a dataclass per export that returns rows. Deduplicate by
    # name — two queries with the same shape and name would collide,
    # but that's a bug in queries.sql and we'd rather fail loudly.
    seen: dict[str, list[Column]] = {}
    for export in exports:
        if export.result_type not in ("Row", "Rows"):
            continue
        cls = export.row_class_name()
        if cls in seen:
            if seen[cls] != export.columns:
                raise ValueError(
                    f"Two queries emit conflicting shapes for {cls}: "
                    f"{seen[cls]!r} vs {export.columns!r}"
                )
            continue
        seen[cls] = export.columns
        lines.append("@dataclass")
        lines.append(f"class {cls}:")
        for col in export.columns:
            lines.append(f"    {col.name}: {py_type_for_column(col)}")
        lines.append("")
        lines.append("")

    for export in exports:
        lines.extend(_func_lines(export))
        lines.append("")
        lines.append("")

    # Trim trailing blank
    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <queries.sql.json>", file=sys.stderr)
        return 1
    source = Path(sys.argv[1])
    report = json.loads(source.read_text())
    sys.stdout.write(generate(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
